"use client";

import { useEffect } from "react";
import { useRealtime } from "@/components/RealtimeProvider";
import { Panel, Empty, useApi, apiSend, timeAgo } from "@/components/ui";

type Notification = { id: number; type: string; title: string; body: string | null; read: boolean; createdAt: string };

const ICONS: Record<string, string> = {
  "bot.connected": "🟢",
  "bot.disconnected": "🔴",
  "bot.created": "🤖",
  "auth.login": "🔐",
  "downloader.success": "📥",
  "downloader.failed": "⚠️",
  "system.warning": "🚨",
};

export default function NotificationsPage() {
  const { data, reload } = useApi<{ notifications: Notification[]; unread: number }>("/api/notifications");
  const { notificationsTick } = useRealtime();

  useEffect(() => {
    void reload();
  }, [notificationsTick, reload]);

  return (
    <Panel
      title="Notifications"
      subtitle="Generated by real engine events"
      right={
        <div className="flex gap-2">
          <button type="button" className="btn" onClick={async () => { await apiSend("/api/notifications", "POST", { all: true }); await reload(); }}>
            ✅ MARK ALL READ
          </button>
          <button type="button" className="btn btn-danger" onClick={async () => { await apiSend("/api/notifications", "DELETE"); await reload(); }}>
            🗑 CLEAR
          </button>
        </div>
      }
    >
      {!data?.notifications.length ? (
        <Empty icon="🔔" title="No notifications" hint="Connect a bot or run a download to generate events." />
      ) : (
        <div className="space-y-2">
          {data.notifications.map((n) => (
            <button
              key={n.id}
              type="button"
              onClick={async () => { await apiSend("/api/notifications", "POST", { id: n.id }); await reload(); }}
              className={`flex w-full items-start gap-3 rounded-xl border p-3 text-left ${n.read ? "border-edge bg-black/20" : "border-[#ff2e4d]/40 bg-[#ff2e4d]/5"}`}
            >
              <span className="text-lg">{ICONS[n.type] ?? "🔔"}</span>
              <span className="min-w-0 flex-1">
                <span className="block text-sm font-semibold text-slate-100">{n.title}</span>
                {n.body && <span className="block text-xs text-slate-400">{n.body}</span>}
                <span className="mt-1 block text-[11px] text-slate-600">{n.type} · {timeAgo(n.createdAt)}</span>
              </span>
              {!n.read && <span className="mt-1 h-2 w-2 rounded-full bg-[#ff2e4d]" />}
            </button>
          ))}
        </div>
      )}
    </Panel>
  );
}
